In [2]:
import pandas as pd
import numpy as np
  
# importing matplotlib module
import matplotlib.pyplot as plt
plt.style.use('default')
  
# %matplotlib inline: only draw static
# images in the notebook
%matplotlib inline

import plotly.express as px

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

In [3]:
path = "./9b._U.S._Regional_Macroeconomic_Data.csv"
Macro = pd.read_csv(path, on_bad_lines='skip')
path = "./7d._U.S._Regional_Electricity_Generation_Electric_Power_Sector.csv"
E_Gen = pd.read_csv(path, on_bad_lines='skip')


# New England

In [18]:
##NEW ENGLAND ECONOMIC INDICATORS##
New_England=Macro[(Macro == 'New England').any(axis=1)] #for new england only 
New_England = New_England.drop(["remove","map","linechart","units","source key"], axis=1)
New_England=New_England

## Nuclear

In [19]:
##GET 
E_Gen_NE = E_Gen.iloc[18:26,:]#New England
E_Gen_NE_Nuclear=E_Gen_NE[(E_Gen_NE=="Nuclear").any(axis=1)]
E_Gen_NE_Nuclear=E_Gen_NE_Nuclear.drop(["remove","map","linechart","units","source key"], axis=1)


In [20]:
reg_data=pd.concat([E_Gen_NE_Nuclear, New_England], ignore_index=True, axis=0).T
reg_data.columns = reg_data.iloc[0] 
reg_data = reg_data.drop("Unnamed: 1").T

In [21]:
reg_data=reg_data.to_numpy()

In [22]:
nuclear=reg_data[0,]
indicators=reg_data[1:,]

In [23]:
df_ind = pd.DataFrame(indicators).T
df_out= pd.DataFrame(nuclear)
df_out_train=df_out[:-2]
df_out_test=df_out[25:]
df_ind_train=df_ind[:-2]
df_ind_test=df_ind[27:]


In [24]:
regr = linear_model.LinearRegression()

In [25]:
regr.fit(df_ind_train, df_out_train)

LinearRegression()

In [26]:
#nuclear_pred = regr.predict(indicators_test)

print("Coefficients: \n", regr.coef_)

#print("Mean squared error: %.2f" % mean_squared_error(nuclear_test, nuclear_pred))

Coefficients: 
 [[ 0.0055115   0.08108661  0.0022785  -0.01219221  0.94822349]]


# Non-Hydro Power Renewable

In [27]:
##GET 
E_Gen_NE = E_Gen.iloc[18:26,:]#New England
E_Gen_NE_Nonhydro=E_Gen_NE[(E_Gen_NE=="Nonhydro renewables").any(axis=1)]
E_Gen_NE_Nonhydro=E_Gen_NE_Nonhydro.drop(["remove","map","linechart","units","source key"], axis=1)

In [28]:
reg_data=pd.concat([E_Gen_NE_Nonhydro, New_England], ignore_index=True, axis=0).T
reg_data.columns = reg_data.iloc[0] 
reg_data = reg_data.drop("Unnamed: 1").T

In [29]:
reg_data=reg_data.to_numpy()

In [30]:
Nonhydro=reg_data[0,]
indicators=reg_data[1:,]
indicators

array([[100.1, 100.6, 100.7, 100.0, 99.0, 98.4, 98.1, 97.5, 96.3, 83.3,
        92.2, 94.7, 95.2, 96.8, 97.3, 98.2, 99.1, 99.8, 99.5, 98.4, 96.3,
        96.2, 96.4, 97.2, 98.1, 98.7, 99.4, 100.2],
       [860.0, 864.0, 874.0, 882.0, 907.0, 905.0, 903.0, 904.0, 904.0,
        971.0, 936.0, 938.0, 1019.0, 974.0, 967.0, 959.0, 949.0, 939.0,
        942.0, 948.0, 951.0, 950.0, 952.0, 956.0, 961.0, 967.0, 973.0,
        979.0],
       [5988.0, 5998.0, 6006.0, 6014.0, 6022.0, 6034.0, 6045.0, 6056.0,
        6019.0, 6010.0, 6016.0, 6026.0, 6038.0, 6063.0, 6078.0, 6090.0,
        6101.0, 6099.0, 6100.0, 6105.0, 6113.0, 6121.0, 6129.0, 6135.0,
        6142.0, 6151.0, 6159.0, 6168.0],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.6, 7.6, 6.4, 6.8, 7.0, 7.1,
        7.1, 7.2, 7.3, 7.4, 7.4, 7.5, 7.5, 7.6, 7.6, 7.5, 7.5, 7.5, 7.5,
        7.5, 7.5]], dtype=object)

In [31]:
df_ind = pd.DataFrame(indicators).T
df_out= pd.DataFrame(Nonhydro)
df_out_train=df_out[:-2]
df_out_test=df_out[25:]
df_ind_train=df_ind[:-2]
df_ind_test=df_ind[27:]


In [32]:
regr = linear_model.LinearRegression()

In [33]:
regr.fit(df_ind_train,df_out_train)

LinearRegression()

In [34]:
#nonhydro_pred = regr.predict(indicators_test)

print("Coefficients: \n", regr.coef_)

#print("Mean squared error: %.2f" % mean_squared_error(Nonhydro_test, nonhydro_pred))

Coefficients: 
 [[ 4.63577879  0.24309191  0.5042938  14.47509685]]


# Mid Continent

In [35]:
##NEW ENGLAND ECONOMIC INDICATORS##
Mid=Macro[(Macro == 'Middle Atlantic').any(axis=1)] #for new england only 
Mid = Mid.drop(["remove","map","linechart","units","source key"], axis=1)
Mid=Mid

In [36]:

E_Gen_MA = E_Gen.iloc[36:44,:]#Mid-at
E_Gen_MA_Nonhydro=E_Gen_MA[(E_Gen_MA=="Nonhydro renewables").any(axis=1)]
E_Gen_MA_Nonhydro=E_Gen_MA_Nonhydro.drop(["remove","map","linechart","units","source key"], axis=1)

In [37]:
reg_data=pd.concat([E_Gen_MA_Nonhydro, Mid], ignore_index=True, axis=0).T
reg_data.columns = reg_data.iloc[0] 
reg_data = reg_data.drop("Unnamed: 1").T

In [38]:
reg_data=reg_data.to_numpy()

In [39]:
Nonhydro=reg_data[0,]
indicators=reg_data[1:,]
indicators

array([[99.9, 100.3, 100.5, 99.9, 98.5, 97.7, 97.1, 96.3, 95.2, 79.9,
        90.2, 92.4, 93.0, 94.3, 94.6, 95.6, 96.4, 97.1, 96.6, 96.0, 94.0,
        93.8, 93.8, 94.4, 94.9, 95.4, 95.9, 96.6],
       [2253.0, 2264.0, 2286.0, 2295.0, 2327.0, 2334.0, 2338.0, 2342.0,
        2350.0, 2534.0, 2479.0, 2412.0, 2660.0, 2498.0, 2477.0, 2439.0,
        2414.0, 2393.0, 2394.0, 2401.0, 2417.0, 2418.0, 2422.0, 2431.0,
        2446.0, 2461.0, 2475.0, 2490.0],
       [16240.0, 16265.0, 16296.0, 16328.0, 16360.0, 16402.0, 16430.0,
        16457.0, 16352.0, 16267.0, 16204.0, 16139.0, 16071.0, 16040.0,
        16076.0, 16101.0, 16123.0, 16115.0, 16114.0, 16125.0, 16140.0,
        16161.0, 16180.0, 16202.0, 16224.0, 16248.0, 16273.0, 16300.0],
       [19.8, 19.8, 19.9, 20.0, 20.0, 20.0, 20.1, 20.1, 20.1, 16.7, 17.9,
        18.4, 18.5, 18.7, 18.9, 19.2, 19.4, 19.6, 19.7, 19.8, 20.0, 19.9,
        19.8, 19.8, 19.8, 19.8, 19.8, 19.8]], dtype=object)

In [40]:
df_ind = pd.DataFrame(indicators).T
df_out= pd.DataFrame(Nonhydro)
df_out_train=df_out[:-2]
df_out_test=df_out[25:]
df_ind_train=df_ind[:-2]
df_ind_test=df_ind[27:]

In [41]:
regr = linear_model.LinearRegression()

In [42]:
regr.fit(df_ind_train, df_out_train)

LinearRegression()

In [43]:
#nonhydro_pred = regr.predict(indicators_test)

print("Coefficients: \n", regr.coef_)

#print("Mean squared error: %.2f" % mean_squared_error(Nonhydro_test, nonhydro_pred))

Coefficients: 
 [[ -9.27777091   0.42257829  -0.42440913 170.79045959]]
